import type { Metadata } from "next";
import { Barlow} from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

const barlow = Barlow({
  subsets : ['latin'],
  variable : "--font-barlow-sans",
  weight : ["200" , "300" , "500" , '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${barlow.variable}  antialiased`}
        >
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
